
services:
  rag-api:
    image: stanlee321/rag-api:latest
    env_file:
      - .env
    ports:
      - "8003:8003"
    depends_on:
      - chroma
  # zipkin:
  #   image: openzipkin/zipkin
  #   ports:
  #     - "9411:9411"
  #   depends_on: 
  #     - otel-collector

  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:0.111.0
  #   command: ["--config=/etc/otel-collector-config.yaml"]
  #   volumes:
  #     - ${PWD}/otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   ports:
  #     - "4317:4317"  # OTLP
  #     - "4318:4318"
  #     - "55681:55681" # Legacy
  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.23
    volumes:
      - index_data:/chroma/chroma
    ports:
      - "8000:8000"
    env_file:
      - configs/chroma.env
    environment:
      - PERSIST_DIRECTORY=/chroma/chroma
      # - CHROMA_OTEL_EXPORTER_HEADERS=${CHROMA_OTEL_EXPORTER_HEADERS:-{}}
      # - CHROMA_OTEL_SERVICE_NAME=${CHROMA_OTEL_SERVICE_NAME:-chroma}
      # - CHROMA_OTEL_GRANULARITY=${CHROMA_OTEL_GRANULARITY:-all}
      # - CHROMA_OTEL_COLLECTION_ENDPOINT=${CHROMA_OTEL_COLLECTION_ENDPOINT:-http://otel-collector:4317/}
      # - CHROMA_SERVER_AUTHN_CREDENTIALS=${CHROMA_SERVER_AUTHN_CREDENTIALS:-chr0ma-t0k3n}
      # - CHROMA_SERVER_AUTHN_PROVIDER=${CHROMA_SERVER_AUTHN_PROVIDER:-chromadb.auth.token_authn.TokenAuthenticationServerProvider}
      # - CHROMA_AUTH_TOKEN_TRANSPORT_HEADER=${CHROMA_AUTH_TOKEN_TRANSPORT_HEADER:-Authorization}

    # depends_on:
    #   - otel-collector
    #   - zipkin


volumes:
  index_data:
    driver: local